micronaut:
    application:
        name: video-microservice
    http:
        client:
            exception-on-error-status: false
            connect-timeout: 3m
datasources:
    default:
        driver-class-name: org.mariadb.jdbc.Driver
        db-type: mariadb
        dialect: MYSQL
jpa:
    default:
        entity-scan:
            packages:
                - com.eng2.assessment.generated.vm.domain
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
netty:
    default:
        allocator:
            max-order: 3