/**
 */
package Y3892609;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Id Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link Y3892609.IdField#getIsAutoGenerated <em>Is Auto Generated</em>}</li>
 * </ul>
 *
 * @see Y3892609.MetamodelPackage#getIdField()
 * @model
 * @generated
 */
public interface IdField extends AField {
	/**
	 * Returns the value of the '<em><b>Is Auto Generated</b></em>' attribute.
	 * The default value is <code>"true"</code>.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Is Auto Generated</em>' attribute.
	 * @see #setIsAutoGenerated(Boolean)
	 * @see Y3892609.MetamodelPackage#getIdField_IsAutoGenerated()
	 * @model default="true"
	 * @generated
	 */
	Boolean getIsAutoGenerated();

	/**
	 * Sets the value of the '{@link Y3892609.IdField#getIsAutoGenerated <em>Is Auto Generated</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Is Auto Generated</em>' attribute.
	 * @see #getIsAutoGenerated()
	 * @generated
	 */
	void setIsAutoGenerated(Boolean value);

} // IdField
