micronaut:
  application:
    name: client
  http:
    client:
      exception-on-error-status: false

client-urls:
  vm:
    videos: http://localhost:8080/videos
    users: http://localhost:8080/users
  thm:
    trending-hashtags: http://localhost:8081/trending-hashtags
  sm:
    subscriptions: http://localhost:8082/subscriptions
    recommendations: http://localhost:8082/recommendations