/**
 */
package Y3892609.impl;

import Y3892609.IdField;
import Y3892609.MetamodelPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Id Field</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link Y3892609.impl.IdFieldImpl#getIsAutoGenerated <em>Is Auto Generated</em>}</li>
 * </ul>
 *
 * @generated
 */
public class IdFieldImpl extends AFieldImpl implements IdField {
	/**
	 * The default value of the '{@link #getIsAutoGenerated() <em>Is Auto Generated</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getIsAutoGenerated()
	 * @generated
	 * @ordered
	 */
	protected static final Boolean IS_AUTO_GENERATED_EDEFAULT = Boolean.TRUE;

	/**
	 * The cached value of the '{@link #getIsAutoGenerated() <em>Is Auto Generated</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getIsAutoGenerated()
	 * @generated
	 * @ordered
	 */
	protected Boolean isAutoGenerated = IS_AUTO_GENERATED_EDEFAULT;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IdFieldImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return MetamodelPackage.Literals.ID_FIELD;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Boolean getIsAutoGenerated() {
		return isAutoGenerated;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setIsAutoGenerated(Boolean newIsAutoGenerated) {
		Boolean oldIsAutoGenerated = isAutoGenerated;
		isAutoGenerated = newIsAutoGenerated;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, MetamodelPackage.ID_FIELD__IS_AUTO_GENERATED,
					oldIsAutoGenerated, isAutoGenerated));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
		case MetamodelPackage.ID_FIELD__IS_AUTO_GENERATED:
			return getIsAutoGenerated();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
		case MetamodelPackage.ID_FIELD__IS_AUTO_GENERATED:
			setIsAutoGenerated((Boolean) newValue);
			return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
		case MetamodelPackage.ID_FIELD__IS_AUTO_GENERATED:
			setIsAutoGenerated(IS_AUTO_GENERATED_EDEFAULT);
			return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
		case MetamodelPackage.ID_FIELD__IS_AUTO_GENERATED:
			return IS_AUTO_GENERATED_EDEFAULT == null ? isAutoGenerated != null
					: !IS_AUTO_GENERATED_EDEFAULT.equals(isAutoGenerated);
		}
		return super.eIsSet(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String toString() {
		if (eIsProxy())
			return super.toString();

		StringBuilder result = new StringBuilder(super.toString());
		result.append(" (isAutoGenerated: ");
		result.append(isAutoGenerated);
		result.append(')');
		return result.toString();
	}

} //IdFieldImpl
