services:
  vm-db:
    environment:
      MARIADB_USER: &vmdbuser video
      MARIADB_PASSWORD: &vmdbpass videosecret
      MARIADB_ROOT_PASSWORD: iamroot
      MARIADB_DATABASE: &vmdbname videos
  thm-db:
    environment:
      MARIADB_USER: &thmdbuser trendingHashtag
      MARIADB_PASSWORD: &thmdbpass hashtagSecret
      MARIADB_ROOT_PASSWORD: iamroot
      MARIADB_DATABASE: &thmdbname trendingHashtags
  sm-db:
    environment:
      MARIADB_USER: &smdbuser subscriptions
      MARIADB_PASSWORD: &smdbpass subscriptionSecret
      MARIADB_ROOT_PASSWORD: iamroot
      MARIADB_DATABASE: &smdbname subscriptions
  vm:
    environment:
      DB_USER: *vmdbuser
      DB_PASSWORD: *vmdbpass
      DB_HOST: vm-db
      DB_NAME: *vmdbname
  thm:
    environment:
      DB_USER: *thmdbuser
      DB_PASSWORD: *thmdbpass
      DB_HOST: thm-db
      DB_NAME: *thmdbname
  sm:
    environment:
      DB_USER: *smdbuser
      DB_PASSWORD: *smdbpass
      DB_HOST: sm-db
      DB_NAME: *smdbname