micronaut:
    application:
        name: video-microservice
datasources:
    default:
        driver-class-name: org.mariadb.jdbc.Driver
        db-type: mariadb
        dialect: MYSQL
jpa:
    default:
        entity-scan:
            packages:
                - com.eng2.assessment.vm.domain
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                hbm2ddl:
                    auto: update
netty:
    default:
        allocator:
            max-order: 3