name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  gradle-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate model
        run: ./gradlew modelling:validate
      - name: Generate code
        run: ./gradlew modelling:codegen
      - name: Build docker images
        run: ./gradlew microservices:video-microservice:dockerBuild microservices:trending-hashtag-microservice:dockerBuild microservices:subscription-microservice:dockerBuild
      - name: Run unit/integration tests
        run: ./gradlew microservices:client:unitTests --continue microservices:video-microservice:test --continue microservices:trending-hashtag-microservice:test --continue microservices:subscription-microservice:test --continue
      - name: Start feature test Docker environment
        run: docker compose -f microservices/client/src/test/resources/compose-feature-tests.yml up --quiet-pull -d --wait
      - name: Run feature tests
        run: DO_NOT_START_TESTCONTAINER=true ./gradlew microservices:client:featureTests
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Gradle tests
          path: ./microservices/*/build/test-results/*/*.xml
          reporter: java-junit