name: Render report PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


permissions: write-all
jobs:
  render-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }} # https://github.com/actions/checkout/issues/317#issuecomment-1221335371
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: ./report/src
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: Y3892609
          path: report/src/main.pdf
      - name: Move and rename PDF as specified in the assessment
        run: mv ./report/src/main.pdf ./Y3892609.pdf
      - name: Add and commit file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./Y3892609.pdf
          git commit -m "Latest report PDF"
          git push

